apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: ubuntu:latest
  - name: my-container-1
    image: nginx:latest
    ports:
    - containerPort: 83
  - name: my-container-2
    image: nginx:latest
    ports:
    - containerPort: 86
