name: Demo-1
run-name: ${{github.actor}} is trying to understand workflows
on:
  push:
   branches:
    - Juveria


jobs:
  runs-on: ubuntu-latest
  
  job-1:
    
    steps:
      - run: echo "Hello Juveria!, Job-1 is done."

  job-2:
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installed python. 
