name: Demo-1
run-name: ${{github.user}} is trying to understand workflows
on:
  push:
    branches:
      - Juveria


jobs:
  job-1:
    runs-on: uuntu-latest
    steps:
      - run: echo "Hello Juveria!, Job-1 is done."
