name: helpers-read-yaml

on:
  push:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
        shell: bash

      - name: Extract Container Port
        run: |
          container_port=$(python -c "import yaml; print(yaml.load(open('pod.yaml', 'r'))['spec']['containers'][0]['ports'][0]['containerPort'])")
          echo "Container Port: $container_port"

      - name: Extract Container Ports
        run: |
            python -c "import yaml; print(yaml.load(open('pod.yaml', 'r'))['spec']['containers'][0]['ports'])"
        id: container_ports

      - name: SSH into Containers
        run: |
          container_ports=$(echo "${{ steps.container_ports.outputs.result }}")
          for port in $container_ports; do
          # Replace <your-ssh-command> with your actual SSH command, and use $port as the port number
          <your-ssh-command> -p $port user@your-server
          done
        shell: bash

