name: helpers-read-yaml

on:
  push:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Extract and SSH on ContainerPorts
        run: |
          yaml_file='pod.yaml'
          container_ports=($(grep 'containerPort' "$yaml_file" | grep '(containerPort: )\d+'))
          for container_port in "${container_ports[@]}"; do
             echo "Container Port: $container_port"
          done

