name: helpers-read-yaml

on:
  push:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
        shell: bash

      - name: Extract Container Port
        run: |
          container_port=$(jq -r '.spec.containers[0].ports[0].containerPort' pod.yaml)
          echo "Container Port: $container_port"
        shell: bash
